<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.11" />

		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.11" />
	</ItemGroup>

	<!-- SOLVIX يعتمد على Business Layer -->
	<ItemGroup>
		<ProjectReference Include="B_Layer\B__Lyer.csproj" />
	</ItemGroup>

	<!-- لا تجعل SOLVIX يجمع ملفات الطبقات مرة ثانية -->
	<ItemGroup>
		<Compile Remove="A_Layer\**" />
		<Compile Remove="B_Layer\**" />
		<EmbeddedResource Remove="A_Layer\**" />
		<EmbeddedResource Remove="B_Layer\**" />
		<None Remove="A_Layer\**" />
		<None Remove="B_Layer\**" />
	</ItemGroup>

	<!-- قاعدة البيانات -->
	<ItemGroup>
		<None Update="SOLVIX.db">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>